### ISSUE TITLE
Need the ability to list orders and list items of an order

### ISSUE THREAD

**Issue by SiyiSun99** [nyu-devops-order/orders#3]
**As a** user
 **I need** the platform can list all orders and all items of an order
 **So that** I can view all orders and all items of an order at one time
   
 ### Details and Assumptions
 * For order:
 * Execute the order query containing in database
 * Serialize the outcome of the query as json
 * Prefer that results are in the order with most recent time order
 * For item:
 * Execute the item query containing in database
 * Serialize the outcome of the item as json
 * Prefer that results are in the order with most recent time order
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given 15 orders
 When I call "GET /orders/list_all_orders" 
 Then it returns all 15 orders in the database in time descending order and all items of an order

 Given order ID
 When I choose to show items of this order like "GET /orders/list_all_items" 
 Then it returns all items of this order in the database
 ```

**Comment by FlipN9** [comment]
Hi Siyi, do we want to add a specification to the issue title such as "Need the ability to list orders associated with a customer ID"?

**Comment by SiyiSun99** [comment]
> Hi Siyi, do we want to add a specification to the issue title such as "Need the ability to list orders associated with a customer ID"?

Yep, I think it should be "Need the ability to list orders for a customer" from readability consideration. Also, I need to add this to **details and assumptions**.

**Comment by mangorr** [comment]
Can also list orders of a customer by providing customer id.
