### ISSUE TITLE
Need the ability to create an order

### ISSUE THREAD

**Issue by FlipN9** [nyu-devops-order/orders#4]
**As a** user
**I need** a way to create an order
**So that** I can place a new order and check the order details and status later

**Details & Assumptions:** 
* An order is created with the following parameters: 
a unique order ID, a customer ID, creation_time, order_status
* An order status could be: PLACED, SHIPPED, DELIVERED, CANCELLED, RETURNED
* An order should have at least one item in it. 

**Acceptance Criteria:**

```gherkin
Given no orders in the database
When I create an order
Then the database should have one order
```

**Comment by zhedebut03** [comment]
Assumptions: An order could exist without any items in it.
